### ISSUE TITLE
A quick question

### ISSUE THREAD

**Issue by MostHated** [zubroide/go-api-boilerplate#1]
Hey there,    
I am still fairly new to go and wanted to try this out. Attempting to run govendor sync as per the instructions says it's no longer in use and to use go mod vendor, which I am still trying to get working, but I noticed this is fairly recently uploaded, but is this an older project that was just uploaded, or is it up to date to try and use/learn from?

Thanks!
-MH

**Comment by mnvx** [comment]
It is fresh project what I created in process of learning Go. You may find more about it here https://habr.com/ru/post/455302/

**Comment by MostHated** [comment]
Understood. I got part of the way there. I went to run the docker-compose but came across this:

```
Step 9/11 : COPY ./docker/go/dbconf.yml ./db/dbconf.yml
 ---> Using cache
 ---> 880883b00233
Step 10/11 : RUN swagger generate spec -o doc/swagger.json     && go install
 ---> Running in 90bd0f6c279e
unable to resolve embedded struct for: ListParametersInterface
3&ast.Ident{NamePos:141000, Name:"ListParametersInterface", Obj:(*ast.Object)(0xc0003fdb30)}
ERROR: Service 'go' failed to build: The command '/bin/sh -c swagger generate spec -o doc/swagger.json     && go install' returned a non-zero code: 1

```

**Comment by mnvx** [comment]
Thanks. Fixed

**Comment by MostHated** [comment]
:+1:  Worked well after that. Thanks!

Just a quick note on the README.md

```
sudo apt update
sudo apt upgrade
# See last version here: https://golang.org/dl/
wget https://dl.google.com/go/go1.12.5.linux-amd64.tar.gz
sudo tar -xvf go1.11.1.linux-amd64.tar.gz // ----------------- 1.12.5
sudo mv go /usr/local
sudo mcedit /etc/profile
```

I would put the ```Install necessary packages``` part just below the ```Clone repo``` part because it was saying to run the install and it took me a second as I wasn't sure what install it was talking about, but that was because I didn't have it yet because I had not cloned the repo first.

Other than that, looks great. : D
